status = [
    "Success"
]
pr_status = [
    "Success"
]
block_labels = [
    "do-not-merge"
]
timeout_sec = 1800
required_approvals = 1
use_codeowners = false
use_squash_merge = false
[committer]
name = "Boyu Yang [Bot]"
email = "yangby@cryptape.com"
